### PR TITLE
Py38

### PR DESCRIPTION
**Pull request by coldfix**

### CODE REVIEW

**Comment by ydutheil** [comment]
Hi,
@rdemaria do you know the status of MADX 5.05.02? It is labelled as *last-release* on CERN's afs but the latest release on github is 5.05.01

**Comment by tpersson** [comment]
We must have forgot to update this on github. The latest offical release is MAD-X 5.05.02

cheers
Tobias
________________________________________

**Comment by ydutheil** [comment]
@tpersson do you think you could tag the associated commit on github? Right now the runner crashes when trying to pull the *5.05.02* tag from the MADX repo

**Comment by coldfix** [comment]
That would be awesome! :+1:

The more difficult issue is that of the C extension on windows... In short: due using fortran we have to build madx with gcc. However, the official python binaries are built using the msvc compiler, specifically using VS2015 starting with python3.5 and hence upgrading to the UCRT. To the last of my knowledge there is not yet a build of mingw that supports the ucrt due to licensing issues. But here is the kicker, python 3.4 which is the last python version with which mingwpy works, has now run out of support. We may have to significantly change the build process in order to be able to produce something again. I'm thinking of building MAD-X as DLL and linking against that. It is kind of expected that this will pose additional runtime requirements on the user for now (possibly manually downloading some DLLs).

See also https://github.com/hibtc/cpymad/issues/32#issuecomment-153695711 Steve Dower's [Building Extensions for Python 3.5](https://stevedower.id.au/blog/building-for-python-3-5), and [mingwpy](https://github.com/mingwpy/mingwpy)

**Comment by rdemaria** [comment]
Thanks a lot of taking care!  numpy/scipy must have the same problem because they rely on fortran libraries. Do you know what it is their solution?

**Comment by coldfix** [comment]
Hacks! I don't know exactly, but I guess they solved by separating their fortran from their C code into separate DLLs, something like cmake's [CMakeAddFortranSubdirectory](https://cmake.org/cmake/help/v3.9/module/CMakeAddFortranSubdirectory.html) which is not feasible for MAD-X because it has cyclic dependencies between C and fortran code.

**Comment by coldfix** [comment]
The other solution is to use intel fortran compiler which is I believe compatible with MSVC.

**Comment by rdemaria** [comment]
I think ifort became kind of free. You can get it from the OneAPI stack
https://software.intel.com/content/www/us/en/develop/tools/oneapi/hpc-toolkit.html

**Comment by rdemaria** [comment]
this is what I found for scipy:
https://docs.scipy.org/doc/scipy/reference/building/windows.html
I don't if it is applicable...

**Comment by coldfix** [comment]
Thanks! That might be helpful. I can't promise though that I'll have some time for this in the near future.

**Pull request merged**
