### PR TITLE
Adding distribution

### PR DESCRIPTION
**Pull request by tpersson**

### CODE REVIEW

**Comment by aoeftiger** [comment]
Thanks @tpersson ! I could indeed make cpymad work with the latest MAD-X v5.06.00 by adding 'DISTlib' in the `libraries` list in `setup.py`. 

+++

With the current master version of cpymad (commit 8e2ef6f) before this PR, I failed to initialise a `Madx()` instance within python and received an `ImportError`:
```python
>>> import cpymad.madx
>>> cpymad.madx.Madx()
[...]
ImportError: Traceback (most recent call last):                                                                     
  File "/cvmfs/aph.gsi.de/debian8/miniconda3/lib/python3.7/site-packages/minrpc/service.py", line 85, in _dispatch  
    response = handler(*args)                                                                                       
  File "/cvmfs/aph.gsi.de/debian8/miniconda3/lib/python3.7/site-packages/minrpc/service.py", line 101, in _dispatch_
function_call
    module = __import__(modname, None, None, '*')
ImportError: /cvmfs/aph.gsi.de/debian8/cpymad/src/cpymad/libmadx.cpython-37m-x86_64-linux-gnu.so: undefined symbol: 
free_distribution
```

**Comment by coldfix** [comment]
Hi,

the first reason that this fails is that you have to update `MADX_VERSION` in `utils/manylinux/build_all`. However, there will be further issues, partly due to MAD-X's cmake config using syntax that doesn't exist in cmake28 (`VERSION_GREATER_EQUAL`). This can be solved by updating `utils/manylinux/cmake28_hotfix.patch`, or possibly by updating to manylinux2010.

However, even then, there might be further issues due to the travis setup, and probably due to the windows build being broken.

I might have some time to finally try and resolve some of these issues next week.

Best, Thomas

**Comment by aoeftiger** [comment]
@coldfix You're referring to the CI checks right?

**Comment by coldfix** [comment]
Yes, sorry for being unclear.

**Pull request closed without merging**
