### PR TITLE
Add equality comparison for ArrayAttribute (issue #89)

### PR DESCRIPTION
**Pull request by chernals**

### CODE REVIEW

**Review by rdemaria — APPROVED** [review]
looks good to me!

**Comment by coldfix** [comment]
Hey, thanks.

I suggest to change the line to `return self._values == other` to allow comparison with native lists and other list-like objects. While at it, maybe add `__le__` as well, so that comparison works same as with lists.

Best also add tests for

- left handed/right handed comparison
- all comparison operators `==`, `!=`, `<`, `<=`, `>`, `>=`
- comparing against builtin lists / other ArrayAttribute instances

**Comment by chernals** [comment]
@coldfix OK, done for the operators.

Do you want unit test for the class? In a new file or within one of the two existing ones?

**Comment by coldfix** [comment]
The same file will be fine, thanks!

**Comment by Oskari-Tuormaa** [comment]
@coldfix I've created a single testcase testing each of the operators. Let me know if you'd rather i restructure it somehow.

**Comment by coldfix** [comment]
Great, thanks!

Looks fine for now. I'll wait for the test to pass and then merge. I might later add a small check for comparisons against plain lists.

**Comment by Oskari-Tuormaa** [comment]
I guess flake8 didn't like my formatting... I've reformatted the lines in question, and doublechecked with flake8; everything seems in order now :+1:

**Pull request merged**
