### PR TITLE
Update MAD-X to 5.08.01

### PR DESCRIPTION
**Pull request by rdemaria**

### CODE REVIEW

**Comment by coldfix** [comment]
Thanks. Just asking: For what is the sphinx-prompt extension needed?

**Comment by rdemaria** [comment]
not sure why, but the update documentation action was failing:

https://github.com/hibtc/cpymad/runs/5360061700?check_suite_focus=true

```
 Extension error:
Could not import extension sphinx-prompt (exception: No module named 'sphinx-prompt')
make: *** [Makefile:53: html] Error 2
make: Leaving directory '/home/runner/work/cpymad/cpymad/doc'
Error: Process completed with exit code 2.
```

**Comment by coldfix** [comment]
Weird. Maybe one of the dependencies added a requirement on this package without adding it to their list of dependencies.

We can merge it like this for now.

**Comment by coldfix** [comment]
Oh nevermind, I seemed to have added this dependency to the sphinx configuration. But can't remember when or why. Might have been by mistake.

**Comment by coldfix** [comment]
I merged and updated the PR to remove the unneeded dependency on sphinx prompt that I have probably added by mistake at some earlier point in time.

**Pull request merged**
