### PR TITLE
access and query beam list

### PR DESCRIPTION
**Pull request by rdemaria**
Introduces get_defined_beam, get_defined_beam_names

### CODE REVIEW

**Comment by coldfix** [comment]
I would probably cut the `_defined` part from the function names, otherwise looks good to me. Should we also add an accessor to the `Madx` class? Something like `.beams`, similar to how the `.sequence` accessor works.

**Comment by rdemaria** [comment]
It could be a good idea to add the mapping but perhaps it would be a bit redundant because the beams other than "default_beam" are usually associated to an existing sequence. Basically, we would have:

```
mad.beam.default_beam == mad.beam
mad.beam.lhcb1 == mad.sequence.lhcb1.beam
mad.beam.lhcb2 == mad.sequence.lhcb2.beam
```

However, the sequence does not have to exist to define a beam! So there would be inaccessible beams...

**Comment by coldfix** [comment]
I see, but what's the point of exposing the list of beams on the low level API then? Couldn't you just do `get_sequence_names` and `get_sequence_beam(seq_name)` instead?

**Comment by rdemaria** [comment]
the reason is to handle those corner cases when the user has defined the beam, but did not "use"d the sequence yet

**Comment by rdemaria** [comment]
Example:
```python
mad=Madx()
mad.input("""beam,sequence="a", pc=1;
beam,sequence="b", pc=1;
beam,sequence="c", pc=1;""")
mad._libmadx.get_beam_names()
['default_beam', 'a', 'b', 'c']
``` but  `mad.sequence.a.beam` would not work because sequence `a` has not been defined yet.

**Comment by rdemaria** [comment]
I added the mapping. Questions is that we want to change:
```
mad.beam -> mad.default_beam 
mad.beams -> mad.beam
```
for consistency

**Comment by coldfix** [comment]
> I added the mapping. Question is if we want to change:
> 
> ```
> mad.beam -> mad.default_beam 
> mad.beams -> mad.beam
> ```
> 
> for consistency

Renaming the mapping to `.beam` would break backward compatibility somewhat (people may have come to expect that `.beam` refers to the command, even though that wasn't documented), so I think it's better to keep it as beams. If we were to break backward compatibility for the sake of consistency at some point, it might be better to rename the other "singular" mappings to plural instead, as was suggested in #51.

**Pull request merged**
