### PR TITLE
expose madx errors

### PR DESCRIPTION
**Pull request by rdemaria**
I implemented a basic support for extracting field errors from the sequence. See this example:

```
from cpymad.madx import Madx
from cpymad import libmadx

mad=Madx()
mad.call("fodo.madx")
qf=mad.sequence['fodo'].expanded_elements['qf']
field_err1=qf._attr['field_errors']

libmadx.start()
libmadx.input('call,file="fodo.madx";')
qf=libmadx.get_expanded_element("fodo",2)
field_err2=qf['field_errors']

print(field_err1)
print(field_err2)
```

where `fodo.madx` contains
```
beam,particle=proton,gamma=1.1;
mq: multipole;
qf: mq,knl:={0,kqf};
qd: mq,knl:={0,kqd};
dr: drift,l:=ld;

kqf=0.8;
kqd=-0.7;
ld=1.2;

fodo : line = (dr,qf,dr,qd);
use,period=fodo;

select, flag=error, range=qf;
efcomp, dkn={ 1e-6, 2e-6,3e-6},
        dks={-1e-6,-2e-6,-3e-6};

twiss;
eprint;
```

### CODE REVIEW

**Comment by coldfix** [comment]
Thanks! I will do some minor cleanup and issue a release soon.

**Comment by coldfix** [comment]
@rdemaria It would also be great to update documentation in `doc/getting-started.rst` or similar for the new feature and maybe add some basic tests in `test/test_madx.py` if you find time.

**Comment by coldfix** [comment]
One more thing, @rdemaria @aoeftiger, I have changed it so that the `elem.field_errors`, etc attributes will always be present, but set to `None` to represent when they are NULL in MAD-X (so you don't have to guard against `AttributeError` everytime you access). It could also be set to an empty numpy array `np.empty(0)` to avoid inhomogenious return type and None-checks altogether. What do you prefer?

**Comment by rdemaria** [comment]
Thanks a lot! Is good for me.

I have seen you have modified the `array_double_copy` to use `_inplace_double_array`. I think this approach is problematic because the returned array will point to garbage after `use,sequence`. Try

```
libmadx.start()
libmadx.input('call,file="fodo.madx";')
qf=libmadx.get_expanded_element("fodo",2)
field_err2=qf['field_errors']
field_err3=field_err2.copy()
libmadx.input('use,sequence=fodo;')

print(field_err2)
print(field_err3)
```

**Comment by coldfix** [comment]
The rationale was that one would usually use the `Madx` class which copies the data to another process anyway (which is needed for parallelization etc). Do you use `libmadx` directly?

The simplest fix is to do `.copy()` on the returned array. I could change the implementation but I would like to do some benchmarks first if it does influence the performance, in particular when reading data from tables.

**Comment by rdemaria** [comment]
I don't use libmadx directly at the moment, but I feel is a bit dangerous leaving potentially crashing code. I agree performance might be an issue, though. Already now looping on an LHC sequence to access some attributes is noticeably slow using the cpymad.madx.Madx interface.

**Comment by coldfix** [comment]
Nothing should crash as long as you copy before calling another MAD-X command (which is always done if you use it in subprocess mode). I think, I would leave the libmadx interface to be a low-level interface that should be as fast as possible and leave it to the user to be responsible how they use it if they really want to use it directly. This also provides the greatest control.

The bulk of performance overhead is likely in IPC. To avoid this overhead, you will probably need to reduce the amount of IPC. This could be done in several ways, e.g.:

- call user functions in the subprocess side that process data directly from libmadx interface before returning the data to the main process. This is currently not straight forward but could be a lot simplified.
- use MAD-X in-process. This will allow only a single instance of course.

By the way, it is also possible to use `Madx` with in-process `libmadx` as follows:

```python
import cpymad.libmadx as libmadx
from cpymad.madx import Madx

m = Madx(libmadx=libmadx)
```

Of course, if you just want one attribute from each element, the fastest method would be to query these attributes using the C API within the subprocess, and then send all the data back in one go. Currently libmadx always queries all attributes from an element, and sends each element individually, which is of course a lot slower. I think there are two ways two solve this:

- provide a API that will query requested attributes from all requested elements and return the data in one go, i.e. specialize for the use-case
- provide a complete binding of the MAD-X API e.g. using SWIG/SIP and simplify calling arbitrary functions within the subprocess, i.e. generalize for unforseen use-cases

**Pull request merged**
