### PR TITLE
Release cpymad v1.9.2

### PR DESCRIPTION
**Pull request by rdemaria**

### CODE REVIEW

**Comment by coldfix** [comment]
Thanks! I tagged the release to trigger an upload to PyPI.

**Comment by rdemaria** [comment]
I added by hand a release note that was missing in https://github.com/hibtc/cpymad/releases . Should I have added the changes in the commit message of the version update?

**Comment by coldfix** [comment]
Hi, yes, the release note defaults to the commit message, which is why I usually copy-paste all the new CHANGES there.

**Comment by rdemaria** [comment]
Noted thanks!

**Pull request merged**
